<?php

namespace AppBundle\Repository;

/**
 * GraduationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraduationRepository extends \Doctrine\ORM\EntityRepository
{
}
