<?php

namespace AppBundle\Repository;

/**
 * SideProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SideProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
