<?php

namespace AppBundle\Repository;

/**
 * ThingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingRepository extends \Doctrine\ORM\EntityRepository
{
}
